# Default values for mongo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: mongo
  tag: 4.0-xenial
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

nfs:
  path: /nfsshare
  server: 127.0.0.1

podSecurityContext: {}

securityContext: {}

service:
  dbServiceType: NodePort
  db:
    port: 27017
    nodePort: 30017

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
