# Default values for free5gc.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  image:
    free5gc: {}
  dbServiceDomain: mongo.default.svc.cluster.local
  nrf:
    addr: 192.168.2.4
  mnCoreBridge:
    subnet: 192.168.3.0/24
  mnAccessBridge:
    subnet: 192.168.3.0/24

amf:
  http:
    addr: 192.168.2.2
  ngap:
    addr: 192.168.3.2
    subnet: 192.168.3.0/24

ausf:
  http:
    addr: 192.168.2.3

nrf:
  http:
    addr: 192.168.2.4

nssf:
  http:
    addr: 192.168.2.5

pcf:
  http:
    addr: 192.168.2.6

udm:
  http:
    addr: 192.168.2.8
  udr:
    addr: 192.168.2.9

udr:
  http:
    addr: 192.168.2.9

ransim:
  mgnt:
    addr: 192.168.2.11
  data:
    addr: 192.168.3.11
  amf:
    ngap:
      addr: 192.168.3.2
