# Default values for smf.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  image:
    free5gc: {}
  mnCoreBridge:
    subnet: 192.168.3.0/24

replicaCount: 1

image:
  repository: steven30801/free5gc-build
  tag: v2.0.2
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

pfcp:
  addr: 192.168.2.10
gtpu:
  addr: 192.168.3.10
  subnet: 192.168.3.0/24

sliceIdx: {}

podSecurityContext: {}

securityContext:
  privileged: true

resources:
  requests:
    intel.com/sriov_net: '1'
  limits:
    intel.com/sriov_net: '1'

nodeSelector: {}

tolerations: []

affinity: {}
